import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  //data products
  const products = [
    {
      id: 1,
      name: "Espresso",
      price: 10000,
      stock: 10,
    },
    {
      id: 2,
      name: "Vanilla Latte",
      price: 20000,
      stock: 20,
    },
    {
      id: 3,
      name: "Caramel Macchiato",
      price: 30000,
      stock: 30,
    },
    {
      id: 4,
      name: "Avocado Toast",
      price: 40000,
      stock: 40,
    },
    {
      id: 5,
      name: "Big Breakfast",
      price: 50000,
      stock: 50,
    },
    {
      id: 6,
      name: "Burger and Fries",
      price: 60000,
      stock: 60,
    },
    {
      id: 7,
      name: "Chicken Wings",
      price: 70000,
      stock: 70,
    },
    {
      id: 8,
      name: "Ribs and Fries",
      price: 80000,
      stock: 80,
    },
    {
      id: 9,
      name: "Steak and Fries",
      price: 90000,
      stock: 90,
    },
    {
      id: 10,
      name: "Wagyu Steak",
      price: 100000,
      stock: 100,
    },
  ];

  const [cart, setCart] = useState([]);
  const [inputId, setInputId] = useState();
  const [inputBayar, setInputBayar] = useState();

  let totalHarga = cart.reduce((a, b) => a + b.price, 0);

  const addToCart = (id) => {
    if (!id) {
      alert("Input Id Product");
      return;
    }

    if (products.find((product) => product.id == id) == undefined) {
      alert("Product not found");
      return;
    }
    const product = products.find((product) => product.id == id);
    setCart([...cart, product]);
    setInputId("");
  };

  const handleBayar = () => {
    if (!inputBayar) {
      alert("Input Nominal Bayar");
      return;
    }
    if (inputBayar < totalHarga) {
      alert("Nominal Bayar Kurang");
      return;
    }
    alert("Kembalian: " + (inputBayar - totalHarga));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mt-10 w-3/4 mx-auto'>
        <div className='flex flex-col'>
          <label htmlFor='name'>Id Products</label>
          <div className='flex'>
            <input
              type='text'
              className='border border-gray-300 rounded-md p-2'
              value={inputId}
              onChange={(e) => setInputId(e.target.value)}
            />
            <button
              onClick={() => addToCart(inputId)}
              className='bg-blue-500 text-white rounded-md p-2'>
              Add to Cart
            </button>
          </div>
        </div>
        <h1 className='text-lg font-bold'>Cart:</h1>
        {cart
          .filter((item, index, self) => {
            return (
              index ===
              self.findIndex((t) => {
                return t.id === item.id;
              })
            );
          })
          .map((item, index) => (
            <div key={index}>
              <p>{item.name}</p>
              <p>{item.price}</p>
              <p>
                Quantity:{" "}
                {cart.filter((cartItem) => cartItem.id == item.id).length}
              </p>
              <hr></hr>
            </div>
          ))}
        <p>
          <b>Total:</b> {totalHarga}
        </p>
        {cart.length == 0 && <p>Cart is empty</p>}
        {JSON.stringify(cart)}
        <div className='flex flex-col'>
          <label htmlFor='name'>Nominal Bayar</label>
          <div className='flex'>
            <input
              type='text'
              className='border border-gray-300 rounded-md p-2'
              value={inputBayar}
              onChange={(e) => setInputBayar(e.target.value)}
            />
            <button
              onClick={() => handleBayar()}
              className='bg-blue-500 text-white rounded-md p-2'>
              Bayar
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
